[pytest]
log_cli = true
log_cli_level = INFO
log_format = %(message)s

markers =
    smoke: смок-тесты
    regression: регрессионные тесты
    critical: критические тесты
    negative: негативные тесты
    filters: тесты фильтров